name: Minify CSS

on:
  push:
    paths:
      - '**.css'
      - '!*.min.css'

permissions:
  contents: write  # Required to push commits. All other permissions are none.

jobs:
  minify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Minify CSS
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'
          output: '.'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-minify CSS"
          file_pattern: '*.min.css'
